### ISSUE TITLE
Regression in 4.23.1: Lock table is created multiple times when using LiquibaseSchema in Postgres

### ISSUE THREAD

**Issue by stijn-vranckx** [liquibase/liquibase#4708]
### Search first

- [X] I searched and no similar issues were found

### Description

The lock table is created multiple times because liquibase thinks the table has not been created yet. This only seems to happen on Postgres. Probably because of the quoting strategy. 
I get the following log messages:

```
Aug 21, 2023 4:41:36 PM liquibase.changelog
INFO: Creating database history table with name: MY_SCHEMA.databasechangelog
Aug 21, 2023 4:41:36 PM liquibase.changelog
INFO: Reading from MY_SCHEMA.databasechangelog
Aug 21, 2023 4:41:40 PM liquibase.command
INFO: Update command encountered an exception.
Aug 21, 2023 4:41:40 PM liquibase.lockservice
WARNING: Failed to release change log lock
Aug 21, 2023 4:41:40 PM liquibase.command
INFO: Command execution complete
Exception in thread "main" liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: relation "databasechangeloglock" already exists [Failed SQL: (0) CREATE TABLE MY_SCHEMA.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]
	at liquibase.command.CommandScope.execute(CommandScope.java:236)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:223)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Liquibase.runInScope(Liquibase.java:1361)
	at liquibase.Liquibase.update(Liquibase.java:215)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)
	at Test.main(Test.java:22)
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: relation "databasechangeloglock" already exists [Failed SQL: (0) CREATE TABLE MY_SCHEMA.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:341)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:258)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:67)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:102)
	at liquibase.command.CommandScope.execute(CommandScope.java:213)
	... 11 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: relation "databasechangeloglock" already exists [Failed SQL: (0) CREATE TABLE MY_SCHEMA.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:39)
	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:121)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:297)
	... 15 more
Caused by: liquibase.exception.DatabaseException: ERROR: relation "databasechangeloglock" already exists [Failed SQL: (0) CREATE TABLE MY_SCHEMA.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:467)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:180)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:145)
	at liquibase.lockservice.StandardLockService.lambda$init$0(StandardLockService.java:121)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$execute$0(ChangelogJdbcMdcListener.java:33)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:32)
	... 17 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "databasechangeloglock" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:461)
	... 27 more
```

### Steps To Reproduce

Run the following code:

```
import liquibase.exception.LiquibaseException;
import liquibase.integration.spring.SpringLiquibase;
import org.postgresql.ds.PGSimpleDataSource;
import org.springframework.jdbc.core.JdbcTemplate;

public class Test {
  public static void main(String[] args) throws LiquibaseException {
    PGSimpleDataSource pgSimpleDataSource = new PGSimpleDataSource();
    pgSimpleDataSource.setURL("jdbc:postgresql://localhost:50266/test");
    pgSimpleDataSource.setPassword("test");
    pgSimpleDataSource.setUser("test");
    JdbcTemplate jdbcTemplate = new JdbcTemplate(pgSimpleDataSource);
    jdbcTemplate.execute("CREATE SCHEMA DEFAULT_SCHEMA");
    jdbcTemplate.execute("CREATE SCHEMA MY_SCHEMA");
    SpringLiquibase springLiquibase = new SpringLiquibase();
    springLiquibase.setDefaultSchema("DEFAULT_SCHEMA");
    springLiquibase.setLiquibaseSchema("MY_SCHEMA");
    springLiquibase.setChangeLog("master.xml");
    springLiquibase.setDataSource(pgSimpleDataSource);
    springLiquibase.afterPropertiesSet();
  }
}
```
with master.xml

```

<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog objectQuotingStrategy="QUOTE_ALL_OBJECTS"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

  <changeSet id="1" author="liquibase">
    <createTable tableName="department">
      <column name="id" type="int">
        <constraints primaryKey="true"/>
      </column>
      <column name="dept" type="varchar(5)">
        <constraints nullable="false"/>
      </column>
      <column name="emp_id" type="int">
        <constraints nullable="false"/>
      </column>
    </createTable>
  </changeSet>

</databaseChangeLog>
```

and pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>Liqui</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
      <version>4.23.1</version>
    </dependency>

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-beans</artifactId>
      <version>5.3.28</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>5.3.28</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-jdbc</artifactId>
      <version>5.3.28</version>
    </dependency>

  </dependencies>

</project>
```

### Expected/Desired Behavior

It works in 4.23.0.
And also when removing the line `springLiquibase.setLiquibaseSchema("MY_SCHEMA");`

### Liquibase Version

4.23.1

### Database Vendor & Version

PostgreSQL 15.1.3

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@tati-qalified - I moved this ticket back to you for review. This looks similar to the problem related to the DATABASECHANGELOG uppercase to lowercase change you see with BigQuery in ticket #5034.

**Comment by filipelautert** [comment]
So if it changed between 4.23.0 and 4.23.1 and it's Postgresql only, that's the only change related to schema/catalog: https://github.com/liquibase/liquibase/pull/4538 .

**Comment by tati-qalified** [comment]
@filipelautert that's strange, because #4538 only involves `setDefaultCatalogName`, which is used for `setDefaultSchema`. The error here is coming from `setLiquibaseSchema`, so **in theory** the PR shouldn't interfere with it.

What I found in the code is that the class `liquibase\database\core\PostgresDatabase.java` does not implement `supportsSchemas` nor `supportsCatalogs`, which are used for both `defaultSchema` and `liquibaseSchema`.

You can see this in `liquibase\integration\spring\SpringLiquibase.java#369` in version 4.18.0, or `liquibase-core\src\main\java\liquibase\integration\spring\SpringLiquibase.java#385` in version 4.25.0

**Comment by kevin-atx** [comment]
@filipelautert This could also be related to, or the same issue as, #5254

**Comment by kevin-atx** [comment]
@filipelautert - When @tati-qalified runs the test with the code supplied by stijn-vranckx with Liquibase v4.23.0, the databasechangelog, databaschangeloglock, and department  tables are created in their correct schemas as follows:

![results-running-v4.23.0](https://github.com/liquibase/liquibase/assets/5502833/a952d409-9180-4f0a-8fd9-e7b6fd577c92)

When she deletes the schemas and reruns the same test with Liquibase v4.23.1, the databasechangelog and databaschangeloglock tables are created in the correct schema but the software gets an error when it tries to create the department table:

![image (20)](https://github.com/liquibase/liquibase/assets/5502833/e5cfd7a8-f57b-4079-99ca-de15fb8c654a)

Please advise.

**Comment by filipelautert** [comment]
> What I found in the code is that the class `liquibase\database\core\PostgresDatabase.java` does not implement `supportsSchemas` nor `supportsCatalogs`, which are used for both `defaultSchema` and `liquibaseSchema`.

@tati-qalified in this case it will use the value from super class that is true.

Bu then the problem may be related to something else and may not be postgresql specific I think. Are you able to reproduce the issue using v4.25.0 ?

**Comment by tati-qalified** [comment]
@filipelautert this same issue is not replicable with v4.25.0, but... there's a casing error. I'll test that part further and open another ticket.

Separating by versions:
v4.23.0 - no issue
v4.23.1 - databasechangeloglock table created multiple times
v4.23.2 - databasechangeloglock table created multiple times
v4.24.0 - creates schema in lowercase, doesn't recognise it in uppercase
v4.25.0 - creates schema in lowercase, doesn't recognise it in uppercase

I wouldn't say that this is fixed by v4.24.0, because to me it seems like it doesn't even get that far in the execution, and it breaks before it can try to create the databasechangeloglock table.

**Comment by tati-qalified** [comment]
Using the CLI and a liquibase.properties file, no matter if the schema name is in upper or lowercase, the commands will run with no issues.

**Comment by filipelautert** [comment]
Hi @tati-qalified - could you check if this still present in 4.28.0 ? There were some fixes related to this in latest versions. Thanks!

**Comment by tati-qalified** [comment]
@filipelautert this issue is fixed with 4.28.0. The DBCL and DBCLL tables are created just once, and the `department` table is created in `default_schema`, as expected.

However, there are casing issues, as the schemas are being created in lowercase, but when setting
```
springLiquibase.setDefaultSchema("DEFAULT_SCHEMA");
springLiquibase.setLiquibaseSchema("MY_SCHEMA");
```
Liquibase is trying to find them in uppercase, so it fails. 

But this ticket can be closed :)
