### PR TITLE
fix: introduce new class ParserSupportedFileExtension to remove hard dependency on snakeyaml for core

### LINKED ISSUE #6491: I cannot exclude "org.yaml:snakeyaml" dependency from LiquiBase
### Search first

- [x] I searched and no similar issues were found

### Description

I want to use LiquiBase with XML changelog. Only XML. I don't need yml, sql, or json.
So I exclude transitive dependencies:

```groovy
implementation('org.liquibase:liquibase-core:4.30.0') {
  transitive: false
}
```

But after upgrading LiquiBase from 4.29.2 to 4.30.0, it doesn't work anymore:

```java
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor

	at liquibase.changelog.DatabaseChangeLog.lambda$load$4(DatabaseChangeLog.java:428)
	at liquibase.util.ExceptionUtil.doSilently(ExceptionUtil.java:68)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:426)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87)
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:231)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.command.CommandScope.execute(CommandScope.java:219)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.Liquibase.runInScope(Liquibase.java:1329)
	at liquibase.Liquibase.update(Liquibase.java:205)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:165)
	at play.modules.liquibase.LiquibaseMigration.runLiquiBase(LiquibaseMigration.java:99)
	at play.modules.liquibase.LiquibaseMigration.migrate(LiquibaseMigration.java:81)
	at play.modules.liquibase.LiquibasePlugin.onApplicationStart(LiquibasePlugin.java:17)
	at play.plugins.PluginCollection.lambda$onApplicationStart$15(PluginCollection.java:232)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:232)
	at play.Play.start(Play.java:243)
	at play.server.Starter.start(Starter.java:12)
	at app.LiquiBaseApp.run(LiquiBaseApp.java:15)
	at ui.petstore.BaseSpec.setUp(BaseSpec.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.BaseConstructor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 44 more
```

### Steps To Reproduce

Create a project with LB dependency _without snakeyaml_:

```groovy
implementation('org.liquibase:liquibase-core:4.30.0') {
  transitive: false
}
```

and `src/main/resources/changelog.xml`.

### Expected result:
LiquiBase works nicely with XML files without "org.yaml:snakeyaml" dependency.

### Actual result:
LiquiBase fails without "org.yaml:snakeyaml" dependency, even if yml format is not used.

### Liquibase Version

4.30.0

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Fixes #6491

This PR removes a indirect dependency on snakeyaml, so people not using yaml/json files can safely exclude snakeyaml from their dependencies.

## Things to be aware of

Analytics also needs to be disabled in order for this fix to work (property `liquibase.analytics.enabled` set to false).

## Things to worry about

We don't have automated tests for it, and creating them would be complicated.

### CODE REVIEW

**Review by MalloD12 — APPROVED** [review]

**Review by wwillard7800 — APPROVED** [review]

**Comment by chadlwilson** [comment]
Thanks for looking at this @filipelautert !

**Review by tati-qalified — APPROVED** [review]

**Review by rberezen — APPROVED** [review]
