### ISSUE TITLE
I cannot exclude "org.yaml:snakeyaml" dependency from LiquiBase

### ISSUE THREAD

**Issue by asolntsev** [liquibase/liquibase#6491]
### Search first

- [x] I searched and no similar issues were found

### Description

I want to use LiquiBase with XML changelog. Only XML. I don't need yml, sql, or json.
So I exclude transitive dependencies:

```groovy
implementation('org.liquibase:liquibase-core:4.30.0') {
  transitive: false
}
```

But after upgrading LiquiBase from 4.29.2 to 4.30.0, it doesn't work anymore:

```java
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor

	at liquibase.changelog.DatabaseChangeLog.lambda$load$4(DatabaseChangeLog.java:428)
	at liquibase.util.ExceptionUtil.doSilently(ExceptionUtil.java:68)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:426)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128)
	at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87)
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:231)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.command.CommandScope.execute(CommandScope.java:219)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.Liquibase.runInScope(Liquibase.java:1329)
	at liquibase.Liquibase.update(Liquibase.java:205)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:165)
	at play.modules.liquibase.LiquibaseMigration.runLiquiBase(LiquibaseMigration.java:99)
	at play.modules.liquibase.LiquibaseMigration.migrate(LiquibaseMigration.java:81)
	at play.modules.liquibase.LiquibasePlugin.onApplicationStart(LiquibasePlugin.java:17)
	at play.plugins.PluginCollection.lambda$onApplicationStart$15(PluginCollection.java:232)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:232)
	at play.Play.start(Play.java:243)
	at play.server.Starter.start(Starter.java:12)
	at app.LiquiBaseApp.run(LiquiBaseApp.java:15)
	at ui.petstore.BaseSpec.setUp(BaseSpec.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.BaseConstructor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 44 more
```

### Steps To Reproduce

Create a project with LB dependency _without snakeyaml_:

```groovy
implementation('org.liquibase:liquibase-core:4.30.0') {
  transitive: false
}
```

and `src/main/resources/changelog.xml`.

### Expected result:
LiquiBase works nicely with XML files without "org.yaml:snakeyaml" dependency.

### Actual result:
LiquiBase fails without "org.yaml:snakeyaml" dependency, even if yml format is not used.

### Liquibase Version

4.30.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by chadlwilson** [comment]
The problem seems to be that #6412 brought in direct dependencies on static variables within `YamlParser` to the `DatabaseChangeLog` which didn't previously exist.

https://github.com/liquibase/liquibase/blob/9f100ba40861e0ac311f276db6d506c9e6679760/liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java#L425-L435

It would be good to restore this ability, excluding these dependencies is useful to reduce security vuln noise and attack surface on dependencies, especially as the poor SnakeYaml project tends to attract a lot of noise from security researchers.

**Comment by ftreede** [comment]
In addition to that spot, snakeyaml is also used to load the remote analytics configuration: 

https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java#L45-L53

Disabling analytics ensures that this code doesn't get called, but the code in the prevous comment DOES still get called.

**Comment by lbadam** [comment]
@asolntsev thanks for filing this issue. We will take a look 👍

**Comment by tati-qalified** [comment]
Hi @asolntsev and @chadlwilson , thank you for reporting this issue and giving details on the problem. This is something that we want to fix, so it will likely be fixed in a future release. When that happens, we'll let you know so you're aware.

Thanks again,
Tatiana
