### ISSUE TITLE
Could not initialize class net.snowflake.client.jdbc.internal.apache.arrow.memory.RootAllocator

### ISSUE THREAD

**Issue by gopisaba** [liquibase/liquibase#3011]
## Environment

**Liquibase Version**:
v4.12.0
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI
**Liquibase Extension(s) & Version**: 
Snowflake (built in library)
**Database Vendor & Version**:
Snowflake
**Operating System Type & Version**:
Mac
**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
AWS

## Description

After upgraded to v4.12.0, Liquibase failing to run.

## Steps To Reproduce

- Upgrade Liquibase to v4.12.0
- Remove snowflake driver from lib as they are built and moved to internal/lib/

## Actual Behavior

Error message
```
[2022-06-27 21:19:02] SEVERE [liquibase.integration] Error executing SQL SELECT MD5SUM FROM LIQUIBASE.DATABASE_CHANGE_LOG WHERE MD5SUM IS NOT NULL: JDBC driver internal error: exception creating result java.lang.NoClassDefFoundError: Could not initialize class net.snowflake.client.jdbc.internal.apache.arrow.memory.RootAllocator at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:560).
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: JDBC driver internal error: exception creating result java.lang.NoClassDefFoundError: Could not initialize class net.snowflake.client.jdbc.internal.apache.arrow.memory.RootAllocator at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:560).
	at liquibase.command.CommandScope.execute(CommandScope.java:162)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
```

## Expected/Desired Behavior
Expecting to run Liquibase after the upgrade

**Comment by kataggart** [comment]
likely duplicate of and will be solved by https://github.com/liquibase/liquibase/issues/3000

**Comment by nvoxland** [comment]
Yes, this should be fixed by #3019
