### ISSUE TITLE
replace remaining uses of snakeyaml Yaml(new Constructor(), ...) with SafeConstructor 

### ISSUE THREAD

**Issue by pjfanning** [liquibase/liquibase#3617]
Due to this CVE: https://github.com/advisories/GHSA-mjmj-j48q-9wg2

**Comment by j-beeler** [comment]
As this is the only way to suggested by the snakeyaml developer to address that CVE, any idea if/when this will happen?

**Comment by pjfanning** [comment]
snakeyaml 2.0 with the CVE fix is out but it breaks API compatibility. In particular

```
2023-02-26T15:12:21.4680779Z Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method <init>()V not found
2023-02-26T15:12:21.4681347Z 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:23)
2023-02-26T15:12:21.4681830Z 	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
```

**Comment by filipelautert** [comment]
Hello @pjfanning ! Liquibase 4.19.1 that is out right now is not using the deprecated API's anymore, so it should work with Snakeyaml 2.0 . Next Liquibase release will depend on Snakeyaml 2.0 .
