### ISSUE TITLE
liquibase-maven-plugin compatibility with sneakyaml 2.0

### ISSUE THREAD

**Issue by Andrej988** [liquibase/liquibase#3940]
### Search first

- [X] I searched and no similar issues were found

### Description

I am trying to update a Spring Boot project using liquibase-maven-plugin with yaml configuration to use snakeyaml 2.0 version.
Versions: 
- Spring Boot 3.0.4 (latest)
- liquibase-maven-plugin 4.20.0 (latest)
- snakeyaml 2.0 (latest)

Same configuration works with snakeyaml 1.33 (previous version which include CVEs).

Problem (see full error stack below):
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:24) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408) ~[liquibase-core-4.17.2.jar:na]

Full Error Stack:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1132) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:907) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.6.jar:6.0.6]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:24) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:393) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:249) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2447) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:236) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:221) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283) ~[liquibase-core-4.17.2.jar:na]
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46) ~[spring-boot-autoconfigure-3.0.4.jar:3.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1808) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-6.0.6.jar:6.0.6]
	... 21 common frames omitted

### Steps To Reproduce

Liquibase maven plugin with YAML config and changelog files.
- Spring Boot 3.0.4 (latest)
- liquibase-maven-plugin 4.20.0 (latest)
- snakeyaml 2.0 (latest)

### Expected/Desired Behavior

Parsing of yaml changelog should not result in errors (works with previous version of snakeyaml).

### Liquibase Version

4.20.0

### Liquibase Extensions

liquibase-maven-plugin

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by FBurguer** [comment]
Hello! The error says that you are using liquibase 4.17.2 insetad of 4.20.0. This issue is already fixed for 4.20.0, try upgrading and let us now if that fixed it. Thanks!

**Comment by Sufyan-wawa** [comment]
Below issue with 4.20.0 and snakeyaml 2.0
![image](https://user-images.githubusercontent.com/114614508/226748803-6874d4a6-29b2-4ff5-8374-df3d2041ad9c.png)

**Comment by Andrej988** [comment]
Hello @FBurguer,

you're right. It was my mistake I raised the liquibase-maven-plugin to a new version but liquibase-core was still using old one.
Thanks for your answer.

**Comment by FBurguer** [comment]
No problem! Happy to help!
