### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/lang3/RandomStringUtils

### ISSUE THREAD

**Issue by RenBrand** [liquibase/liquibase#5934]
### Search first

- [X] I searched and no similar issues were found

### Description

After Upgrading from Version 4.26.0 to 4.27.0 a compile/runtime dependency to `org.apache.commons.lang3.RandomStringUtils` has been added. This dependency was previously only a test-dependency and with https://github.com/liquibase/liquibase/commit/3daa688c6a99ed131687036ba4e40cd743c4b3c8 this becomes a transitive dependency during the runtime. The error occurs on startup with a fresh DB on which the hole setup (including the creation of the databasechangelog-table) has to be done.

### Steps To Reproduce

1. create a new empty DB
2. start a spring-boot application which automatically runs the DB-migration on startup

During the startup the following error happens:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: org/apache/commons/lang3/RandomStringUtils
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
	... 61 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/RandomStringUtils
	at liquibase.util.StringUtil.randomIdentifer(StringUtil.java:765)
	at liquibase.Scope.generateScopeId(Scope.java:154)
	at liquibase.Scope.<init>(Scope.java:147)
	at liquibase.Scope.enter(Scope.java:222)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:168)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.configuration.ConfigurationValueUtils.convertDataType(ConfigurationValueUtils.java:22)
	at liquibase.configuration.ConfiguredValue.getValue(ConfiguredValue.java:40)
	at liquibase.configuration.LiquibaseConfiguration.getCurrentConfiguredValue(LiquibaseConfiguration.java:149)
	at liquibase.configuration.ConfigurationDefinition.getCurrentConfiguredValue(ConfigurationDefinition.java:106)
	at liquibase.configuration.ConfigurationDefinition.getCurrentConfiguredValue(ConfigurationDefinition.java:90)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1835)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	... 74 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.RandomStringUtils
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1353)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1165)
	... 90 common frames omitted
```

### Expected/Desired Behavior

The DB should be initialized with all its tables and no extra dependency to `org.apache.commons.lang3.RandomStringUtils` should be needed.

### Liquibase Version

4.27.0

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@RenBrand - This is a new library that was added recently. Could you check your POM file and see if you're excluding this import. If you are, please remove the exclusion. If not, please let us know so we can look into this further.

**Comment by RenBrand** [comment]
@kevin-atx In our application we only use commons-lang3 in tests and hence it only has scope "test" and we do not exclude it explicitly anywhere. The application itself doesn't (and shouldn't) use this dependency at all.

**Comment by MalloD12** [comment]
Hi @RenBrand.

I think the defined `test` scope could be causing this issue. Could you please try removing the test scope from your pom?

Thanks,
Daniel.

**Comment by kevin-atx** [comment]
@RenBrand - it looks like we recently added the `org.apache.commons.lang3.RandomStringUtils` library as required. That is why you are now seeing the NoClassDefFound error. You will need to add `org.apache.commons.lang3.RandomStringUtils` to your POM as a new library required by liquibase-core.

**Comment by RenBrand** [comment]
@kevin-atx - this adds another library (~600KB) we don't use with a lot of new functionality we don't use neither. This adds also to the footprint of your library which only uses one small function from the entire library, so is it really worth the usage?

**Comment by JeppNils** [comment]
I've also had this problem and would prefer not to need to ship this dependency, but i understand the reasons for adding it. 

However, you have it (Apache Commons Lang) as an example of a dependency you do not include in this section of your documentation: https://contribute.liquibase.com/code/architecture/dependencies/
For completeness I feel you should update that section.

Best regards,
Nils Tornberg

**Comment by MalloD12** [comment]
> I've also had this problem and would prefer not to need to ship this dependency, but i understand the reasons for adding it.
> 
> However, you have it (Apache Commons Lang) as an example of a dependency you do not include in this section of your documentation: https://contribute.liquibase.com/code/architecture/dependencies/ For completeness I feel you should update that section.
> 
> Best regards, Nils Tornberg

That's right, @JeppNils! We have created an internal [ticket](https://datical.atlassian.net/browse/PD-4826) to update this page. Thank you for pointing this out.

@AMBERMW13 - @adrian-velonis1: could you guys look at that ticket when you have time?  I'll close this one as we will address documentation in a separate (internal) ticket.

Daniel.

**Comment by adrian-velonis1** [comment]
[DOC] https://datical.atlassian.net/browse/PD-4826

Changes made and awaiting approval. Will be live shortly.
