### ISSUE TITLE
Build failure after upgrading liquibase version to 4.32.0

### ISSUE THREAD

**Issue by zenith7781** [liquibase/liquibase#7143]
### Search first

- [x] I searched and no similar issues were found

### Description

My issue may seem similar to #6982 but its actually a bit different. Initially my liquibase version was 4.22.0, but I had to upgrade liquibase to 4.32.0. After upgrade, the maven build fails with the following stack trace:

java.util.ServiceConfigurationError: liquibase.database.DatabaseConnection: com.datical.liquibase.ext.database.jvm.SnowflakeProJdbcConnection Unable to get public no-arg constructor
    at java.util.ServiceLoader.fail (ServiceLoader.java:586)
    at java.util.ServiceLoader.getConstructor (ServiceLoader.java:679)
    at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService (ServiceLoader.java:1240)
    at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext (ServiceLoader.java:1273)
    ....... (more frames)
Caused by: java.lang.NoClassDefFoundError: net/snowflake/client/jdbc/internal/org/bouncycastle/operator/OperatorCreationException
    at java.lang.Class.getDeclaredConstructors0 (Native Method)
    at java.lang.Class.privateGetDeclaredConstructors (Class.java:3549)
    at java.lang.Class.getConstructor0 (Class.java:3754)
    ....... (more frames)
Caused by: java.lang.ClassNotFoundException: net.snowflake.client.jdbc.internal.org.bouncycastle.operator.OperatorCreationException
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    ...... (last frames)

2025:07:23-08:30:16 [ERROR] Error setting up or running Liquibase:
2025:07:23-08:30:16 [ERROR] liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:h2:/tmp/APLPLB with driver org.h2.Driver

My project is a spring boot project with spring boot version 3.5.3

### Steps To Reproduce

Here is the pom.xml file (also provided as attachment)

[pom-XML.txt](https://github.com/user-attachments/files/21388272/pom-XML.txt)

 of the component which might be useful.

Please note that the url is correct and the other dependency versions are auto managed by spring boot through the parent component.

### Expected/Desired Behavior

The build is supposed to complete without any failures. Should only use the driver required by reading the jdbc connection url unless explicitly instructed. Also Liquibase job should be successful in postgres, sqlserver, h2 and other databases.

### Liquibase Version

4.32.0

### Database Vendor & Version

h2

### Liquibase Integration

spring boot

### Additional Context

I tried these things but **didn't work**:

1. Used liquibase version 4.33.0 after seeing #6982 but it gave the same error and didn't print the stack trace
2. Added the snowflake-jdbc dependency but didn't help. However I want liquibase to use the default h2 jdbc driver as interpreted from the jdbc connection url in attached given pom.xml
3. Excluded the two artifacts (liquibase-snowflake-pro and liquibase-snowflake) from liquiabase-core:         
<img width="341" height="163" alt="Image" src="https://github.com/user-attachments/assets/d916967d-f57f-43d8-9d0e-56556851e04e" />

3. I am upgrading Liquibase 4.32.0 since it has to be compatible with postgresql driver 42.7.5 onwards (but that seems unrelated here)
Let me know if you need some more information on this. Any help will be appreciated. Thank You

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by zenith7781** [comment]
I noticed one more thing today. If I keep the liquibase core as 4.32.0 and keep the liquibase-maven-plugin as 4.22.0, then the build gets passed. So something is going on with the liquibase-maven-plugin I suppose. Still its my assumption only, and @filipelautert or any other relevant person will be the better people to confirm

**Comment by petepickerill** [comment]
Thanks @zenith7781.  This is strange behavior.  We'll see if we can't isolate it to core liquibase or the hibernate plugin.  We'll let you know what we find.

**Comment by tati-qalified** [comment]
Hi @zenith7781, I've been trying to replicate this issue but haven't been successful. Going by your stack trace it seems like the Snowflake exception is not actually stopping the execution, as the true cause of the error is written after the `[ERROR]` tags:
```
2025:07:23-08:30:16 [ERROR] Error setting up or running Liquibase:
2025:07:23-08:30:16 [ERROR] liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:h2:/tmp/APLPLB with driver org.h2.Driver
```

This error does not necessarily mean that it's a driver issue. 
I noticed that in your pom file you haven't specified username or password. Are you setting them in another place? 

Apart from that, could you try again with Liquibase 5.0.1?

Please let me know how it goes.
Thank you,
Tatiana

**Comment by zenith7781** [comment]
Hi @tati-qalified , apologies for not providing an update. The snowflake error stack trace actually didn't cause the build to fail. It disappeared once I tried 4.33.0 and the build failure was due to a locally cached mv.db file. Everytime I change the liquibase version, deleting that file first and then retriggering the build does the job. Thanks for your response.

Best Regards,
Zenith

**Comment by tati-qalified** [comment]
@zenith7781 I'm glad the issue was resolved for you. Thank you for reaching out!
