### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/opencsv/exceptions/CsvMalformedLineException

### ISSUE THREAD

**Issue by fateh288** [liquibase/liquibase#6192]
### Search first

- [X] I searched and no similar issues were found

### Description

Seeing the following error in stack trace. Although **the functionality seems to work fine**, the exception is indicating some exception which should have been caught and handled suitably but due to missing class/jar in liquibase it is not being handled. 
Need to understand why this exception is thrown and if there should be a suitable dependency in liquibase that provides this class to handle the exception.

Full stack trace:

```
java.util.ServiceConfigurationError: liquibase.change.Change: Provider liquibase.change.core.LoadDataChange could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_232]
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_232]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_232]
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.plugin.AbstractPluginFactory.findAllInstances(AbstractPluginFactory.java:100) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.plugin.AbstractPluginFactory.getPlugins(AbstractPluginFactory.java:62) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.change.ChangeFactory.create(ChangeFactory.java:113) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.ChangeSet.toChange(ChangeSet.java:609) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:544) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.ChangeSet.load(ChangeSet.java:468) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:1069) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNodeHelper(DatabaseChangeLog.java:471) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:461) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:428) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:1010) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNodeHelper(DatabaseChangeLog.java:499) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:461) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:428) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:1010) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNodeHelper(DatabaseChangeLog.java:499) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:461) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:428) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.CommandScope.execute(CommandScope.java:220) ~[liquibase-core-4.29.0.jar:?]
        at LiquibaseCommandDriver.executeLiquibaseCommand(LiquibaseCommandDriver.java:29) ~[]
        at LiquibaseCommandDriver.update(LiquibaseCommandDriver.java:51) ~[]
        at LiquibaseUpdateDriverMain.lambda$main$0(LiquibaseUpdateDriverMain.java:76) ~[]
        at liquibase.Scope.lambda$child$0(Scope.java:191) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:190) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:257) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:261) ~[liquibase-core-4.29.0.jar:?]
        at LiquibaseUpdateDriverMain.main(LiquibaseUpdateDriverMain.java:49) ~[]
Caused by: java.lang.NoClassDefFoundError: com/opencsv/exceptions/CsvMalformedLineException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_232]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_232]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_232]
        ... 40 more
Caused by: java.lang.ClassNotFoundException: com.opencsv.exceptions.CsvMalformedLineException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_232]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_232]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_232]
java.util.ServiceConfigurationError: liquibase.change.Change: Provider liquibase.change.core.LoadUpdateDataChange could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_232]
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_232]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_232]
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:24) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.plugin.AbstractPluginFactory.findAllInstances(AbstractPluginFactory.java:100) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.plugin.AbstractPluginFactory.getPlugins(AbstractPluginFactory.java:62) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.change.ChangeFactory.create(ChangeFactory.java:113) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.ChangeSet.toChange(ChangeSet.java:609) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:544) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.ChangeSet.load(ChangeSet.java:468) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:1069) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNodeHelper(DatabaseChangeLog.java:471) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:461) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:428) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:1010) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNodeHelper(DatabaseChangeLog.java:499) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:461) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:428) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:1010) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNodeHelper(DatabaseChangeLog.java:499) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:461) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:428) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.command.CommandScope.execute(CommandScope.java:220) ~[liquibase-core-4.29.0.jar:?]
        at LiquibaseCommandDriver.executeLiquibaseCommand(LiquibaseCommandDriver.java:29) ~[]
        at LiquibaseCommandDriver.update(LiquibaseCommandDriver.java:51) ~[]
        at LiquibaseUpdateDriverMain.lambda$main$0(LiquibaseUpdateDriverMain.java:76) ~[]
        at liquibase.Scope.lambda$child$0(Scope.java:191) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:190) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:257) ~[liquibase-core-4.29.0.jar:?]
        at liquibase.Scope.child(Scope.java:261) ~[liquibase-core-4.29.0.jar:?]
        at LiquibaseUpdateDriverMain.main(LiquibaseUpdateDriverMain.java:49) ~[]
Caused by: java.lang.NoClassDefFoundError: com/opencsv/exceptions/CsvMalformedLineException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_232]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_232]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_232]
        ... 40 more
Caused by: java.lang.ClassNotFoundException: com.opencsv.exceptions.CsvMalformedLineException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_232]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_232]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_232]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_232]
        ... 40 more
```

### Steps To Reproduce

My driver class looks similar to the below code.
The issue is observed irrespective of the command name - I am personally seeing the issue for "tagExists" and "update" command

```
public class LiquibaseIssue {
  private static CommandResults executeLiquibaseCommand(String commandName,
      HashMap<String, Object> commandSpecificArguments) throws CommandExecutionException {
    final String url = factory.getUrl();
    final String username = factory.getUsername();
    final String password = factory.getPassword();
    final String driver = factory.getDriver();
    CommandScope commandScope = new CommandScope(commandName);
    commandScope.addArgumentValue("url", url);
    commandScope.addArgumentValue("username", username);
    commandScope.addArgumentValue("password", password);
    commandScope.addArgumentValue("driver", driver);
    for (String argumentName : commandSpecificArguments.keySet()){
      commandScope.addArgumentValue(argumentName, commandSpecificArguments.get(argumentName));
    }
    return commandScope.execute();
  }
  public static void main( String[] argv) throws Exception {
    Scope.child(Scope.Attr.resourceAccessor, new ClassLoaderResourceAccessor(), () -> {
      HashMap<String, Object> tagParams = new HashMap<>();
      tagParams.put("tag", "v1");
      CommandResults result = executeLiquibaseCommand("tagExists", tagParams);
    });
  }
}
```

### Expected/Desired Behavior

The exception should not be thrown (My functionality seems to be working fine so I would like to know what might be going wrong if indeed it is a fatal exception)
If thrown, NoClassDefFoundError should not be thrown and should be handled gracefully

### Liquibase Version

4.29.0, 4.26.0

### Liquibase Integration

Java Application (CommandScope API)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @fateh288, thank you for reporting this issue. With the latest Liquibase version 4.30.0 there have been improvements to the logs and to exception handling. Could you upgrade to 4.30.0 and try this again?
Let me know if the problem persists.

Thank you,
Tatiana

**Comment by fateh288** [comment]
Hi @tati-qalified 
I tried using the latest version, the issue is not fixed in 7.30.0

**Comment by tati-qalified** [comment]
@fateh288 are you getting any more / new information with the logs?

**Comment by fateh288** [comment]
@tati-qalified 
No, same errors and same logs.
Is there any specific you are looking for I can provide ?

**Comment by ponziani** [comment]
We're experiencing the same problem after upgrading from 4.25 to 4.32 

It looks the Import-Package entries for 'com.opencsv' are missing in the Manifest file, which is a problem for our OSGi application.

**Comment by vmikhailenko** [comment]
We in private project got similar problem when we use `liquibase` in test case and excluded `opencsv` from it.

What weird is that we got this only on Java 25.

**Comment by Lonzak** [comment]
We also have this issue when using 4.33 and I just saw that I explicitly excluded it in the pom.xml since we do not use 'loadData' (to load data from a CSV file into an existing table).
Until 4.19 this was working fine. Did something change in this area that openCSV is now mandatory?

**Comment by tati-qalified** [comment]
@Lonzak what Java version are you using? Is it 25 as well?

**Comment by Lonzak** [comment]
No I'm using Java 17.

**Comment by tati-qalified** [comment]
Could you upgrade to Liquibase 5.0.1 and try again? Let me know if the problem persists

**Comment by rberezen** [comment]
This issue has been inactive for an extended period with no response to the last request for information. Closing as stale. Please reopen if this is still an issue.
