### ISSUE TITLE
Build from `master` does not include commons-io.jar in the distribution, leading to runtime error

### ISSUE THREAD

**Issue by catull** [liquibase/liquibase#6369]
### Search first

- [X] I searched and no similar issues were found

### Description

Up until 4.29.2. this used to work.

```
liquibase \
    --defaults-file=local/liquibase.properties \
    --changeLogFile="TEST.oracle.sql" \
    --includeObjects="table:TEST" \
    generateChangeLog
```

Also happens for change log file named TEST.oracle.xml.

Now it fails with an Exception:

```
Unexpected error running Liquibase: org/apache/commons/io/output/WriterOutputStream
  - Caused by: org.apache.commons.io.output.WriterOutputStream

For more information, please use the --log-level flag
```

Adding an `---log-level=TRACE` does not produce any extra output.
The same output is generated.

### Steps To Reproduce

Either checkout from `master` or from the tag `tags/v4.29.3`.

Build a distribution, install it, use it to extract data from say an Oracle DB.

### Expected/Desired Behavior

generate-changelog should be working again, as before.

### Liquibase Version

4.29.3, master

### Database Vendor & Version

Oracle 19c

### Additional Context

See issue #6310 for more information.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by catull** [comment]
Last I checked, it was still working with 2661c51bf5edb8fc4e533fba6748c152c26c9429 in `master`, so the bug was introduced after that commit.

**Comment by filipelautert** [comment]
Hi @catull , that's weird.... The error `Unexpected error running Liquibase: org/apache/commons/io/output/WriterOutputStream`  fells like a `noClassDefFoundError `, as if the `commons-io` library was missing from your `internal/lib` directory.

**Comment by catull** [comment]
@filipelautert  Oh no, the class is there.
And I still get the error from `master`.

**Comment by catull** [comment]
It is hidden in `internal/lib/snowflake-jdbc.jar` as

```shell
unzip -v internal/lib/snowflake-jdbc.jar | fgrep WriterOutputStream
    5608  Defl:N     2740  51% 01-22-2020 15:10 abb27513  net/snowflake/client/jdbc/internal/apache/commons/io/output/WriterOutputStream.class
```

**Comment by catull** [comment]
Well, you are right about commons-io.jar not being in internal/lib/.
It is in the distribution of version 4.29.2's internal/lib.

Adding it to internal/lib/ makes the CLI call succeed.

I will change the title of this bug.

**Comment by catull** [comment]
It also does not include `liquibase-commercial.jar`.

**Comment by filipelautert** [comment]
@catull  Hm... maybe it was caused by https://github.com/liquibase/liquibase/pull/6117 ? Could you try reverting this PR and see if it fixes your issue?

**Comment by catull** [comment]
Thanks @filipelautert 

Created "revert pull request" https://github.com/liquibase/liquibase/pull/6417.

It fixes `generateChangelog` CLI.
And it closes this very issue, #6369.

**Comment by filipelautert** [comment]
Thanks for finding and fixing the issue @catull !

**Comment by catull** [comment]
Thanks, @filipelautert , for pointing me into the right direction.
